variables:
  dockerhub_repo: "mozmeao/combinedingress"

docker-build:
  stage: build
  tags:
    - oregon-b-shell
  script:
    - docker build --pull -t "$dockerhub_repo:`cat VERSION`" .

docker-push:
  stage: deploy
  tags:
    - oregon-b-shell
  script:
    - docker tag "$dockerhub_repo:`cat VERSION`" "$dockerhub_repo:`cat VERSION | awk -F. '{print $1 }'`"
    - docker tag "$dockerhub_repo:`cat VERSION`" "$dockerhub_repo:latest"
    - docker push "$dockerhub_repo:`cat VERSION`"
    - docker push "$dockerhub_repo:`cat VERSION | awk -F. '{print $1 }'`"
    - docker push "$dockerhub_repo:latest"
  only:
    - master
