variables:
  dockerhub_repo: "mozmeao/combinedingress"

docker-build:
  stage: build
  tags:
    - mozmeao
  script:
    - docker build --pull -t "$dockerhub_repo:`cat VERSION`" .

docker-push:
  stage: deploy
  tags:
    - mozmeao
  script:
    - export version=`cat VERSION`
    - export short_version=`cat VERSION | awk -F. '{print $1 }'`
    - echo $version
    - echo $short_version
    - docker tag "$dockerhub_repo:$version" "$dockerhub_repo:$short_version"
    - docker tag "$dockerhub_repo:$version" "$dockerhub_repo:latest"
    - docker push "$dockerhub_repo:$version"
    - docker push "$dockerhub_repo:$short_version"
    - docker push "$dockerhub_repo:latest"
  only:
    - master
