variables:
  dockerhub_repo: "mozmeao/combinedingress"


docker-build:
  stage: build
  tags:
    - oregon-b-shell
#  before_script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "dockerhub_repo:`cat VERSION`" .
    - docker push "dockerhub_repo:`cat VERSION`"
#  only:
#    - master